ALTER TABLE GAME
	ADD
		CONSTRAINT FK_MEMBER
		FOREIGN KEY (
			MEMBER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);

ALTER TABLE GAME_BOARD
	ADD
		CONSTRAINT FK_MEMBER_GAME_BOARD
		FOREIGN KEY (
			WRITER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);

ALTER TABLE GAME_BOARD_REPLY
	ADD
		CONSTRAINT FK_GAME_BOARD_GAME_BOARD_REPLY
		FOREIGN KEY (
			PARENT_SEQ
		)
		REFERENCES GAME_BOARD (
			SEQ
		);

ALTER TABLE GAME_BOARD_REPLY
	ADD
		CONSTRAINT FK_MEMBER_GAME_BOARD_REPLY
		FOREIGN KEY (
			WRITER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);

ALTER TABLE GAME_BOARD_FILE
	ADD
		CONSTRAINT FK_GAME_BOARD_GAME_BOARD_FILE
		FOREIGN KEY (
			PARENT_SEQ
		)
		REFERENCES GAME_BOARD (
			SEQ
		);

ALTER TABLE CASH
	ADD
		CONSTRAINT FK_MEMBER_GAME_BOARD_FILE
		FOREIGN KEY (
			MEMBER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);

ALTER TABLE HELPER
	ADD
		CONSTRAINT FK_MEMBER_HELPER
		FOREIGN KEY (
			MEMBER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);

ALTER TABLE CONSULTING_BOARD
	ADD
		CONSTRAINT FK_MEMBER_CONSULTING_BOARD
		FOREIGN KEY (
			WRITER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);

ALTER TABLE CONSULTING_BOARD_REPLY
	ADD
		CONSTRAINT FK_CONSULTING_BOARD_REPLY
		FOREIGN KEY (
			PARENT_SEQ
		)
		REFERENCES CONSULTING_BOARD (
			SEQ
		);

ALTER TABLE CONSULTING_BOARD_REPLY
	ADD
		CONSTRAINT FK_MEMBER_CONSULT_BD_REP
		FOREIGN KEY (
			WRITER_SEQ
		)
		REFERENCES MEMBER (
			NO
		);
		
ALTER TABLE CONSULTING_BOARD_FILE
	ADD
		CONSTRAINT FK_CONSULTING_BOARD_FILE
		FOREIGN KEY (
			PARENT_SEQ
		)
		REFERENCES CONSULTING_BOARD (
			SEQ
		);
		
ALTER TABLE ANONYMOUS_BOARD_FILE
	ADD
		CONSTRAINT FK_ANONYMOUS_BOARD_FILE
		FOREIGN KEY (
			PARENT_SEQ
		)
		REFERENCES ANONYMOUS_BOARD (
			SEQ
		);

ALTER TABLE ANONYMOUS_BOARD_REPLY
	ADD
		CONSTRAINT FK_ANONYMOUS_BOARD_REPLY
		FOREIGN KEY (
			PARENT_SEQ
		)
		REFERENCES ANONYMOUS_BOARD (
			SEQ
		);

