/* GAME DB */

DROP TABLE GAME_RESULT;

DROP SEQUENCE GAME_RESULT_SEQ;

/* GAME RESULT */
CREATE TABLE GAME_RESULT (
	PLAYER_SEQ NUMBER, /* 회원번호 */
	GAME_NO NUMBER, /* 게임회차 */
	PLAYER_REMAINING NUMBER, /* 회원잔액 */
	BET_AMOUNT NUMBER, /* 배팅금액 */
	THIS_AMOUNT NUMBER, /* 금회금액 */
	GAME_NAME VARCHAR2(255) /* 게임종류 */
);

CREATE SEQUENCE GAME_RESULT_SEQ INCREMENT BY 1;

INSERT INTO GAME_RESULT(GAME_NO, PLAYER_SEQ,  PLAYER_REMAINING, BET_AMOUNT, THIS_AMOUNT, GAME_NAME) 
VALUES(GAME_RESULT_SEQ.NEXTVAL,1, 1000, 100, -100,'사다리');

SELECT * FROM GAME_RESULT WHERE PLAYER_SEQ='1';

DELETE FROM GAME_RESULT WHERE PLAYER_SEQ='1';

